import '../styles/globals.css'
import type { AppProps } from 'next/app'
import Layout from '../components/Layout'
import Head from 'next/head'

function MyApp({ Component, pageProps }: AppProps) {
  return (
    <Layout>
      <Head>
        <title>Bay Owl Studios</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favi.ico" />
      </Head>
      <Component {...pageProps} />
    </Layout>
  )
}

export default MyApp
