import React from 'react'

function Terms() {
    return (
        <div className='text-white bg-darkBlue pt-30'>
            <div className='max-w-7xl mx-auto space-y-2 mt-40 my-10'>

                <p className='text-xl font-bold'>Bay Owl Studios Online</p>
                <p>Online Services Terms &amp; Conditions of Use</p>
                <p>(Updated: September 9, 2022)</p>
                <p>This website (&ldquo;Website&rdquo;) is the property of and is operated by Bay Owl Studios. References to &ldquo;Bay Owl Studios&rdquo;, &ldquo;Bay Owl Studio Services&rdquo;, &ldquo;Bay Owl Studios Online&rdquo;, &ldquo;Bay Owl Studios Online Services Portal&rdquo;, &ldquo;bayowl.studio&rdquo;, &ldquo;we&rdquo;, &ldquo;us&rdquo; or &ldquo;our&rdquo; shall also be deemed to be references to Bay Owl Studios or its wholly owned and controlled affiliates.</p>
                <h2>I. ACCEPTANCE OF TERMS &amp; CONDITIONS</h2>
                <p>Access and Acceptance: Your access to and use of the Bay Owl Studios Online website (&ldquo;Website&rdquo;) and the services referred to below (&ldquo;Services&rdquo;) is subject to these terms and conditions. By accessing and/or using the Bay Owl Studios Online website located at:<a href="https://www.bayowlstudios.com/">&nbsp;www.bayowlstudios.com</a> (the &ldquo;Website&rdquo;) and/or the Bay Owl Studios Services (defined below) you signify your agreement to the following (i) terms and conditions (the &ldquo;Terms and Conditions&rdquo;), and (ii) Bay Owl&rsquo;s Privacy Policy, found at&nbsp;<a href="https://www.bayowlstudios.com/privacy-policy/">https://www.bayowlstudios.com/privacy-policy/</a>, and incorporated herein by reference, and accept and agree to be bound by them, whether or not you register with Bay Owl Studios. (&ldquo;Agreement&rdquo;). Where applicable under law, these terms and conditions constitute a &lsquo;writing signed by you&rsquo;. IF YOU DO NOT WISH TO BE BOUND BY THESE TERMS AND CONDITIONS OR THE BAY OWL PRIVACY POLICY, YOU MUST CEASE USING THE WEBSITE/ SERVICES. Nothing stated in these terms and conditions confers any rights or benefits to third-parties.</p>
                <p>Right to Amend Terms: Bay Owl Studios reserves the right at our sole discretion to change, modify, add or delete portions of these terms and conditions at any time without further notice. If we do this, we will post the changes to these terms and conditions on this page and will indicate the effective date at the top, but you should regularly review our terms and conditions to stay abreast of updated changes at<a href="https://www.capitolstudiosonline.com/terms-of-use/">&nbsp;https://www.bayowlstudios.com/terms-of-use/</a>). If you do not agree to (or cannot comply with) the Agreement as amended, your only remedy is to stop using the Website/Services.</p>
                <h2>II. THE SERVICES</h2>
                <p>Services: These terms and conditions are applicable to each user of the Website, including users who upload content on the Website. &ldquo;Content&rdquo; refers to sounds, music, song lyrics, audio files, data, text information and any other materials you may upload to the Website, email directly, or upload to a drive link given by us. The Website offers digital mixing, mastering and other post production audio services in various formats. In addition to mixing and mastering, the &ldquo;Services&rdquo; refer to all aspects of Bay Owl Studios, including but not limited to all current or future products, software and services offered through the Bay Owl Studios Website, including software and other applications.</p>
                <p>The Service may incorporate links to third party websites that are not owned by or under the control of Bay Owl Studios. Bay Owl Studios Online does not control and assumes no liability for the content, privacy policies, or practices of third party websites that are incorporated. Bay Owl Studios Online is not obligated to monitor, censor, or edit the content from third party websites. By using the Website and agreeing to our terms and conditions, you explicitly release Bay Owl Studios Online from any and all liability that results from your interactions with any third-party website.</p>
                <p>We urge all users to be informed when you exit the Service or Website and to fully read the terms and conditions and privacy policy of each other website that you visit.</p>
                <h2>III. AGE RESTRICTION</h2>
                <p>You must be at least 18 years of age to register and use the Services.</p>
                <p>If you are under 18 years of age, you may use this Website only with the consent and supervision of a parent or guardian.</p>
                <h2>IV. USE OF THE WEBSITE AND SERVICES</h2>
                <p>Bay Owl Studios Online hereby grants you permission to access and use the Service as set forth in the Terms and Conditions, so long as:</p>
                <p>You are solely responsible for any Content (as defined in Section 6) submitted by you.</p>
                <p>A)You agree not to:</p>
                <p>(i)distribute any part of the service in any way or through any channel;</p>
                <p>(ii)alter, change, or make any modifications to any part of the Service;</p>
                <p>(iii)use the Service for any commercial uses whatsoever, including but not limited to the (i) the sale of access thereto; or (ii) use on behalf of a third party without first obtaining approval from Bay Owl Studios in writing;</p>
                <p>(iv)use the Website or Services to send junk email, spam, chain letters, pyramid schemes or any other unsolicited messages, commercial or otherwise;</p>
                <p>(v)use this Website or any of the Services to submit, upload, display, transmit, disseminate or otherwise use and/or upload any Content that is false and/or defamatory, inaccurate, abusive, vulgar, obscene, profane, hateful, harassing, sexually oriented, threatening, invasive of anyone&rsquo;s privacy, or violates any law;</p>
                <p>(vi)threaten, abuse, disrupt, stalk or otherwise violate the legal rights of others;</p>
                <p>(vii)upload, post or disseminate any information or Content in any manner that infringes any copyright, trademark, patent or other proprietary right of any party or infringes any intellectual property law or other applicable law;</p>
                <p>(viii)restrict or inhibit any other user from using and enjoying the Website or any of the Services;</p>
                <p>(ix)use the website/Services in any manner that could damage, disable, overburden or impair the Website/Services or interfere with any other party&rsquo;s use and enjoyment of the Website/Service;</p>
                <p>(x)transmit any Content, information or software that contains a virus, worm, time-bomb, cancelbot, trojan horse or other harmful, disruptive, or deleterious component;</p>
                <p>(xi)you will not utilise any automated systems, including but not limited to any robot, spider, site search/retrieval application, or any other manual or automated technique to scrape, index, data mine, etc., or in any way reproduce or circumvent the navigational structure or presentation of the Bay Owl Studios Online system, the Services, or the contents of such Website or Services.</p>
                <p>(xii)impersonate any other individual or entity in connection with your use of this Website or any of the Services;</p>
                <p>(xiii)use the Services to distribute files illegally or violate the rights of others to copy and distribute protected work.</p>
                <p>B)You further agree, represent and warrant that:</p>
                <p>(i)you solely own or otherwise control all of the rights to the Content that you submit to the Website and that you are not prohibited from submitting the Content to Bay Owl Studios by any other agreement or obligation;</p>
                <p>(ii)all information and details you provide is accurate, complete and current;</p>
                <p>(iii)if you are not a consumer, you confirm that you have the authority to bind any business on whose behalf you use the Website/Services.</p>
                <p>(iv)In addition, you acknowledge that by using this Website and/or the Services, you are not submitting Content for the purpose of consideration by any music label associated with or affiliated with Bay Owl Studios and your Content will not be reviewed for purposes of submission to any label.</p>
                <p>(v)if you are availing of our independent artist promos you agree that you are in fact independent, and as such not signed with a music label.</p>
                <h2>V. BAY OWL STUDIOS ONLINE USER ACCOUNTS</h2>
                <p>User Account: You are required to complete the registration process in order to open a Bay Owl Studios Online User Account to use certain services and features. Such a process requires the provision of certain information by you and the registration of a username and password, so please provide accurate information. You are responsible for maintaining the confidentiality of the username and password. You are fully responsible for the use by any unauthorised person of the Website/Services, including all financial charges and legal liability that he or she may incur. We recommend that you change your password from time to time for additional security.</p>
                <p>Unauthorised Access: You agree to immediately notify Bay Owl Studios Online in the event of a breach or unauthorised use of your account. In no event will we be liable for any indirect or consequential loss or damage whatsoever resulting from the disclosure of your username and or password. You may not use another person&rsquo;s account at any time.</p>
                <p>Although Bay Owl Studios Online will not be liable for your losses caused by your account being breached or an unauthorised use, you may be liable for the losses caused to Bay Owl Studios Online or others by virtue of an unauthorised use.</p>
                <p>Account Deletion: In the sole discretion of Bay Owl Studios and at any time with or without prior notice, Bay Owl Studios may purge any and all of its files associated with your account and your Content. As a result, it is your responsibility to keep a copy(ies) of the original and mixed files and or Content. If you request an additional copy of your mixed file from Bay Owl Studios, we may not be able to provide one for you, and you release Bay Owl Studios, Bay Owl Studios and its affiliates from any related liability in connection therewith.</p>
                <p>Customer Service: Users may contact Bay Owl Studios Online via the contact us feature for any questions, comments, or concerns about the Service and/or any other related concerns.</p>
                <h2>VI. YOUR CONTENT AND CONDUCT</h2>
                <p>6.1. Bay Owl Studios Online account holders are permitted to submit Content to the Service, including but not limited to information, metadata, recorded music tracks, written compositions, authorisations, instructions, songs, graphic files or any other information or music files in any required specification or medium (collectively, &ldquo;Content&rdquo;). Users understand that Bay Owl Studios does not absolutely guarantee any confidentiality with any Content users submit. Content is not limited solely to that content that is uploaded to the Service. Any content received by Bay Owl Studios Online on your behalf, via any mode of delivery, shall be deemed to be your Content.</p>
                <p>6.2. You are solely responsible for your own Content and the consequences of submitting and publishing your Content on the Service. You affirm that you are the owner or possess the necessary licenses, rights, consent, and permissions to publish user content you submit to Bay Owl Studios; you also agree to license all intellectual property and proprietary rights in the user content to Bay Owl Studios Online for publication and processing on and through the Service pursuant to these terms and conditions of Service.</p>
                <p>6.3 You retain all existing ownership rights in and to your Content. Notwithstanding the ownership as aforesaid, by submitting your Content to Bay Owl Studios Online, you hereby grant us a worldwide, non-exclusive, royalty-free, sub-licensable and transferable license to access, use, reproduce, distribute, prepare derivative works of, display, and perform your Content in connection with the Services, including without limitation, for promotion and distribution of all or part of the Services, including derivative works, in any media formats and media channels.</p>
                <p>6.4 You further agree that you grant Bay Owl Studios the worldwide, non-exclusive, royalty-free, sub-licensable and transferable license to display and otherwise use your artist(s) and/or label name and logo (if you have one) and all artwork, song and album titles, all trademarks, service marks, logos and trade names, and all artist, songwriter, producer and mixer names and approved likenesses, each as embodied in metadata within your Content or otherwise provided by you, on our Website, within the Service, and in any marketing, advertising, or promotional materials for our Service.&nbsp;</p>
                <p>6.5 You further agree that Bay Owl Studios Online may retain, (but not display, distribute, or perform) server copies of your Content that have been removed or deleted. Additionally, we may, in our sole discretion and without furnishing any prior intimation to you, decline to provide the Services to you, and/or remove any of your Content that has already been uploaded to the Service or displayed on our Website.</p>
                <p>6.6 You further agree that any Content you submit to the Service will not contain third party copyrighted material, or material that is subject to other third party proprietary rights, unless you have permission from the rightful owner of the material or you are otherwise legally entitled to utilise the material and to grant Bay Owl Studios Online all of the license rights granted herein. For example, you cannot upload Content that consists of &ldquo;cover versions&rdquo;, remixes, or recordings that include third party samples unless you have all necessary written permissions from the rights holders of such content, including but not limited to songwriters and owners of the applicable original recordings and/or compositions.</p>
                <p>6.7 You further agree that you will not submit to the Service any Content or other material that is contrary to all applicable local, national, and international laws and regulations.</p>
                <p>6.8 You further agree that it is your responsibility to deliver all necessary Content, including any information, metadata, recorded music tracks, compositions, instructions, songs, graphic files or any other information or music in any required specifications as may be required for Bay Owl Studios online to perform the requested Service(s), and you acknowledge that Bay Owl Studios Online will not be obligated to furnish its services hereunder until acceptable receipt of such Content.</p>
                <p>6.9 Bay Owl Studios Online does not endorse any Content submitted to the Service by any user or other licensor, or any opinion, recommendation, or advice associated with and/or expressed therein, and Bay Owl Studios expressly disclaims any and all liability in connection with Content you provide. Bay Owl Studios does not permit copyright infringing activities and infringement of intellectual property rights on the Service, and Bay Owl Studios Online will remove any/all Content upon proper notification that such Content infringes on another&rsquo;s intellectual property rights. Bay Owl Studios Online reserves the right to remove Content without prior notice.</p>
                <h2>VII. PRICING, TAXES AND COMMENCEMENT OF SERVICES</h2>
                <p>Pricing: You agree to pay all charges, including postage, shipping and handling charges,&nbsp;if applicable,&nbsp;at the prices in effect when such charges are incurred. You are solely responsible for paying any applicable taxes relating to your purchases.</p>
                <p>Payment: Payments hereunder to Bay Owl Studios must be by debit or credit card, UPI, or any other payment mode made available by our payment processing merchant.</p>
                <p>Commencement of Services; Refunds. You give Bay Owl Studios permission to commence the performance of its Services prior to the expiry of any &ldquo;cooling off&rdquo; period which might otherwise apply following your receipt of the recorded tracks submitted to Bay Owl Studios. Bay Owl Studios does not provide any refunds of payment subsequent to work commencing on the Services.&nbsp;</p>
                <p>7.4 Revisions. Bay Owl Studios will provide a set number of revisions free of charge as per your selected package, additional revisions will be chargeable.</p>
                <h2>VIII. TRADEMARK AND COPYRIGHT INFORMATION</h2>
                <p>With the above-mentioned restrictions, the following additional conditions apply specifically to the use of Bay Owl Studios&rsquo; content.</p>
                <p>All Bay Owl Studios&rsquo; content and material on this website (&ldquo;Bay Owl Materials&rdquo;), including, but not limited to text, data, graphics, logos, button icons, images, audio clips, video clips, links, digital downloads, data compilations, and software is owned, controlled by, or licensed to Bay Owl Studios and is protected by copyright, trademark and other intellectual property rights. The Bay Owl Materials on this website are made available solely for your personal, non-commercial use and may not be copied, reproduced, republished, modified, uploaded, posted, transmitted or distributed in any way, including by email or other electronic means, without the express prior written consent of Bay Owl Studios in each instance. You may download material intentionally made available for downloading from this website for your personal, non-commercial use only, provided that you keep intact any and all copyright and other proprietary notices that may appear on such Bay Owl Materials.</p>
                <p>Bay Owl Studios provides such Bay Owl Materials &ldquo;as is.&rdquo;</p>
                <p>When using the Service, users may be exposed to Bay Owl Studios Materials from various sources</p>
                <h2>IX. INDIAN COPYRIGHT (AMENDMENT) ACT, 2012</h2>
                <p>If you are a copyright owner or an agent thereof and believe that any Bay Owl Materials or Content uploaded to or hosted on the Service infringes upon your copyrights, you may submit a notification pursuant to the Indian Copyright (Amendment) Act, 2012, by providing us with all the required information as per the specific statute.</p>
                <h2>X. BAY OWL STUDIOS CREDIT</h2>
                <p>To the extent you are in compliance with these terms and conditions and choose to credit Bay Owl Studios with respect to any recording that has been mixed and/or mastered by Bay Owl Studios Online for release to the public, we hereby grant you the limited, revocable right to include the following approved credit, in the form specified in section 10.1 below. Please include within such credit only the specific Service(s) that were provided to you by Bay Owl Studios:</p>
                <p>10.1 Approved Credit Language: &ldquo;[Mixed] [and] [Mastered] by [Engineer Name] at Bay Owl Studios.&rdquo;&nbsp;</p>
                <p>10.2 Approved Credit Image: For the purpose of credit, you may use the Bay Owl Studio Logo alongside the approved credit language. For this purpose we would provide you with a hi-res image of the Bay Owl Studio logo.&nbsp;</p>
                <p>10.3 Any such approved credit shall be included in a suitable place in the inner sleeve liner notes of the CD or other recording and shall be in the same size, typeface and font as any other similar information included in such liner notes. For the avoidance of doubt, Bay Owl Studios does not grant you any permission whatsoever to include any additional information other than the approved credit language and image specified in sections 10.1 and 10.2 above, including but not limited to Bay Owl Studios&rsquo; or its affiliates&rsquo; and/or imprints&rsquo; logo(s), imagery, trademarks, or the Bay Owl Studios mixing or mastering engineer(s) names, or any other Bay Owl Studios information and/or intellectual property, in any manner, or on any medium.</p>
                <h2>XI. GRANT OF LICENCE</h2>
                <p>You hereby grant Bay Owl Studios and its affiliates a non-exclusive, royalty-free, fully paid up, perpetual, irrevocable and fully sub-licensable right and license to reproduce, modify, adapt, publish, translate, create derivative works from, distribute, display and otherwise use the Content you provide throughout the world in any media for the purpose of promoting the Bay Owl Studios Services.</p>
                <h2>XII. PRIVACY</h2>
                <p>We are committed to protecting your privacy. We will only use the information that we collect about you lawfully. Please refer to our&nbsp;<a href="https://www.bayowlstudios.com/privacy-policy/">privacy policy</a>.</p>
                <h2>XIII. ARCHIVING</h2>
                <p>Bay Owl Studios makes no representation or warranty that it shall retain any Content once the requested work has been completed and the relevant Content downloaded by you and, therefore, cannot be held responsible for any partial or complete loss of any Content. Without prejudice to the foregoing, you give Bay Owl Studios permission to retain and/or archive copies of Content following the download of the relevant completed Content by you.</p>
                <h2>XIV. EXCLUSION OF WARRANTIES</h2>
                <p>EXCEPT AS EXPRESSLY STATED IN THIS AGREEMENT, THE WEBSITE AND STUDIO PRODUCTS AND SERVICES ARE PROVIDED &ldquo;AS IS&rdquo; AND &ldquo;AS AVAILABLE&rdquo; WITH NO REPRESENTATIONS OR WARRANTIES OF ANY KIND, EITHER EXPRESS OR IMPLIED, INCLUDING, BUT NOT LIMITED TO, ANY IMPLIED WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, AND NON-INFRINGEMENT. BAY OWL STUDIOS MAKES NO WARRANTIES OR REPRESENTATIONS ABOUT THE ACCURACY OR COMPLETENESS OF THIS SITE&rsquo;S CONTENT OR THE CONTENT OF ANY SITES LINKED TO THIS SITE AND ASSUMES NO LIABILITY OR RESPONSIBILITY FOR ANY (I) ERRORS, MISTAKES, OR INACCURACIES OF CONTENT, (II) PERSONAL INJURY OR PROPERTY DAMAGE, OF ANY NATURE WHATSOEVER, RESULTING FROM YOUR ACCESS TO AND USE OF OUR STUDIOS AND SERVICES, (III) ANY UNAUTHORISED ACCESS TO OR USE OF OUR SERVERS AND/OR ANY AND ALL PERSONAL INFORMATION AND/OR FINANCIAL INFORMATION STORED THEREIN, (IV) ANY INTERRUPTION OR CESSATION OF TRANSMISSION TO OR FROM OUR SERVICES, (IV) ANY BUGS, VIRUSES, TROJAN HORSES, OR THE LIKE WHICH MAY BE TRANSMITTED TO OR THROUGH OUR SERVICES BY ANY THIRD PARTY, AND/OR (V) ANY ERRORS OR OMISSIONS IN ANY CONTENT OR FOR ANY LOSS OR DAMAGE OF ANY KIND INCURRED AS A RESULT OF THE USE OF ANY CONTENT PROCESSED, POSTED, EMAILED, TRANSMITTED, OR OTHERWISE MADE AVAILABLE VIA THE SERVICES. YOU ASSUME TOTAL RESPONSIBILITY AND RISK FOR YOUR USE OF THIS WEBSITE AND THE SERVICES.</p>
                <h2>XV. LIMITATION OF LIABILITY</h2>
                <p>TO THE FULL EXTENT PERMITTED BY LAW, BAY OWL STUDIOS AND ITS AFFILIATES ARE NEITHER RESPONSIBLE NOR LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, CONSEQUENTIAL, SPECIAL, EXEMPLARY, PUNITIVE, OR OTHER DAMAGES ARISING OUT OF OR RELATING IN ANY WAY TO THIS WEBSITE, THE STUDIOS, THE PRODUCTS, THE SERVICES, OR YOUR USE THEREOF. THIS LIMITATION APPLIES WHETHER THE ALLEGED LIABILITY IS BASED ON CONTRACT, TORT, NEGLIGENCE, STRICT LIABILITY, OR ANY OTHER BASIS, EVEN IF BAY OWL STUDIOS HAS BEEN ADVISED OF THE POSSIBILITY OF SUCH DAMAGE. BAY OWL STUDIOS DOES NOT WARRANT THAT THE FUNCTIONS CONTAINED IN THIS WEBSITE OR THE SERVICES WILL BE UNINTERRUPTED OR ERROR-FREE, THAT DEFECTS WILL BE CORRECTED, OR THAT THIS WEBSITE OR THE SERVERS THAT MAKE THEM AVAILABLE, ARE OR WILL BE FREE OF VIRUSES OR OTHER HARMFUL COMPONENTS. BAY OWL STUDIOS DOES NOT WARRANT OR MAKE ANY REPRESENTATIONS REGARDING THE USE OR THE RESULTS OF THE USE OF THE WEBSITE OR THE SERVICES IN TERMS OF THEIR CORRECTNESS, ACCURACY, TIMELINESS, RELIABILITY, OR OTHERWISE. YOU (AND NOT BAY OWL STUDIOS) ASSUME THE ENTIRE COST OF ALL NECESSARY MAINTENANCE, REPAIR, OR CORRECTION OF ANY SUCH MATERIALS.</p>
                <p>NOTWITHSTANDING ANY OTHER PROVISION OF THIS AGREEMENT, YOU AND BAY OWL STUDIOS HEREBY AGREE THAT THE MAXIMUM AGGREGATE LIABILITY OF BAY OWL STUDIOS TO YOU FOR ANY CLAIMS ARISING FROM OR RELATED TO THE SERVICES WHETHER IN CONTRACT, TORT OR OTHERWISE, SHALL BE LIMITED TO AN AMOUNT EQUAL TO THE RESPECTIVE FEE PAID BY YOU.</p>
                <p>If you are a consumer this Section 15 does not affect your statutory rights.</p>
                <h2>XVI. TERMINATION</h2>
                <p>We have the right to terminate our provision of the Services to you at any time.</p>
                <h2>XVII. VOID WHERE PROHIBITED</h2>
                <p>Although this website is accessible worldwide, the Services discussed or referenced on this website are available to all persons or in all geographic locations. We reserve the right to limit, in our sole discretion, the provision of service to any person or geographic area. The Services shall be deemed to be unavailable/void where prohibited.</p>
                <h2>XVIII. INDEMNIFICATION</h2>
                <p>You remain solely responsive for your Content and you agree to indemnify, defend and hold harmless Bay Owl Studios, affiliates, officers, employees and agents from and against all claims, judgments, losses, expenses, damages and costs, including reasonable attorneys&rsquo; fees, arising out of or resulting from any violation or alleged violation by you of this Agreement, including, but not limited to your transmission of the Content and Bay Owl Studio&rsquo;s use of Content in connection with the Services and as set forth herein. Bay Owl Studios reserves the right to assume and control the exclusive defence of any matter subject to indemnification by you.</p>
                <h2>XIX. MISCELLANEOUS PROVISIONS</h2>
                <p>19.1 Governing Law &ndash; This Agreement and claims directly or indirectly arising out of this Agreement shall be governed by and construed in accordance with the laws of the state of Maharashtra, India, and each party consents to the exclusive jurisdiction of the district of Greater Mumbai, for the adjudication of any disputes arising out of or related to this Agreement.</p>
                <p>19.2 Severability &ndash; If any provision or term of this Agreement, not being of a fundamental nature, is held to be invalid, illegal or unenforceable: (a) the validity, legality and enforceability of the remainder of this Agreement shall not be affected; and (b) with respect to a particular jurisdiction, the applicable provision shall not be affected in any other jurisdiction. Each provision of this Agreement is hereby declared to be separate, severable and distinct.</p>
                <p>19.3 Entire Agreement &ndash; This Agreement constitutes the entire agreement between the parties hereto pertaining to the subject matter hereof, and any and all written or oral agreements heretofore existing between the parties with respect to the subject matter of this Agreement are expressly cancelled.</p>
                <p>19.4 Relationship between the Parties &ndash; There is no joint venture, partnership, agency or fiduciary relationship existing between the parties, and the parties do not intend to create any such relationship by this Agreement.</p>
                <p>19.5 No Third-Party Beneficiaries &ndash; Nothing in this Agreement is intended to give nor gives any person (whether natural or legal) who is not a party to it, any rights.</p>
                <p>19.6 Force Majeure &ndash; We will not be held responsible for any delay or failure to comply with our obligations under this Agreement if the delay or failure arises from any cause which is beyond our reasonable control. This does not affect your statutory rights.</p>
                <p>Bay Owl Studios reserves the right to modify or cease operations of the Studios and any Services at any time without notice.</p>
            </div>
        </div>
    )
}

export default Terms